[server]
headless = true
address = "localhost"
port = 5000

[theme]
# Atom One Dark inspired theme
primaryColor = "#61AFEF"
backgroundColor = "#282C34"
secondaryBackgroundColor = "#3E4451"
textColor = "#ABB2BF"
font = "sans serif"